# Generated by Django 4.1.7 on 2023-03-14 11:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0028_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='achievements',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='additional_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=500, null=True), blank=True, default=list, null=True, size=None), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='communication_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, default=list, null=True, size=None), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='in_game_user_id',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='looking_for_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='roles_rating',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='time_available',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='years_of_exp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_lft_lfp_post',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vouch_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='vouches',
            field=models.ManyToManyField(blank=True, default=None, related_name='vouches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='featured_communities',
            field=models.ManyToManyField(blank=True, default=None, related_name='featuredCommunities', to='page3.community'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='game',
            field=models.CharField(choices=[('Valorant', 'Valorant'), ('Call of Duty', 'Call of Duty'), ('League of Legends', 'League of Legends'), ('Counter Strike: GO', 'Counter Strike: GO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='rank',
            field=models.CharField(choices=[('Val', [('IRON', 'Iron'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum '), ('Diamond', 'Diamond'), ('Ascendant', 'Ascendant'), ('Immortal', 'Immortal'), ('Radiant', 'Radiant')]), ('COD', [('Rookie', 'Rookie'), ('Veteran', 'Veteran'), ('Elite', 'Elite'), ('Pro', 'Pro'), ('Master', 'Master'), ('Grandmaster', 'Grandmaster'), ('Legendary', 'Legendary')]), ('LOL', [('IRON', 'Iron'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum '), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger')]), ('CS', [('Silver', 'Silver'), ('Gold', 'Gold'), ('Master Guardian', 'Master Guardian'), ('Distinguished Master Guardian', 'Distinguished Master Guardian'), ('Legendary', 'Legendary'), ('Elite', 'Elite')])], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='region',
            field=models.CharField(choices=[('Val', [('APAC', 'APAC'), ('EMEA', 'EMEA'), ('NA', 'NA'), ('LATAM', 'LATAM')]), ('COD', [('APAC', 'APAC'), ('EMEA', 'EMEA'), ('NA', 'NA')]), ('LOL', [('APAC', 'APAC'), ('EMEA', 'EMEA'), ('NA', 'NA')]), ('CS', [('APAC', 'APAC'), ('EMEA', 'EMEA'), ('NA', 'NA'), ('LATAM', 'LATAM')])], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(blank=True, default=None, related_name='communities', to='page3.community'),
        ),
        migrations.CreateModel(
            name='Main_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_gamer_profile', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='page3.gameprofile')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
